apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jd-analytics-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - analytics.deere.com
      secretName: jd-analytics-tls
  rules:
    - host: analytics.deere.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: jd-analytics-backend
                port:
                  number: 9000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jd-analytics-frontend
                port:
                  number: 5001
